version: "3.9"
services:
  mysql:
    image: mysql/mysql-server:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ROOT_HOST: "%"
  phabricator:
    depends_on:
      - mysql
    build: ./7.4-apache
    ports:
      - "80:80"
    restart: always
    environment:
      MYSQL_HOST: mysql
      MYSQL_USER: root
      MYSQL_PASS: root
      PHABRICATOR_HOST: 127.0.0.1
